apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: playground
  namespace: argocd
spec:
  description: Playground Project
  sourceRepos:
    - https://github.com/Alixmixx/deploy_amuller_42
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'