# Constants
CPU = 4
MEMORY = 4096
IP_SERVER = "192.168.56.110"
ALPINE_VERSION = "319"
BOX_VERSION = "4.3.12"

Vagrant.configure("2") do |config|
    config.vm.define "#{ENV['USER']}S" do |server|
        server.vm.box = "generic/alpine#{ALPINE_VERSION}"
        server.vm.box_version = "#{BOX_VERSION}"
        server.vm.hostname = "#{ENV['USER']}S"
        server.vm.network "private_network", ip: "#{IP_SERVER}"
        server.vm.provider "virtualbox" do |vb|
            vb.name = "#{ENV['USER']}S"
            vb.customize ["modifyvm", :id, "--cpus", CPU]
            vb.customize ["modifyvm", :id, "--memory", MEMORY]
            vb.linked_clone = true
        end
        server.ssh.insert_key = true
        config.vm.synced_folder "confs", "/vagrant/confs", type: "nfs", nfs_version: 4, nfs_udp: false
        server.vm.provision "shell", path: "./scripts/server.sh"
    end
end